export enum AuditEventMessageSchemaVersion {
  V1 = 1
}

export enum AuditEventMessageCategory {
  FORM = 'FORM',
  ENTITLEMENT = 'ENTITLEMENT'
}

export enum AuditEventMessageSource {
  FORMS_MANAGER = 'FORMS_MANAGER',
  FORMS_DESIGNER = 'FORMS_DESIGNER',
  ENTITLEMENT = 'ENTITLEMENT'
}

export enum AuditEventMessageType {
  FORM_CREATED = 'FORM_CREATED',
  FORM_PUBLISHED = 'FORM_PUBLISHED',
  FORM_TITLE_UPDATED = 'FORM_TITLE_UPDATED',
  FORM_ORGANISATION_UPDATED = 'FORM_ORGANISATION_UPDATED',
  FORM_TEAM_NAME_UPDATED = 'FORM_TEAM_NAME_UPDATED',
  FORM_TEAM_EMAIL_UPDATED = 'FORM_TEAM_EMAIL_UPDATED',
  FORM_SUPPORT_CONTACT_UPDATED = 'FORM_SUPPORT_CONTACT_UPDATED',
  FORM_SUPPORT_PHONE_UPDATED = 'FORM_SUPPORT_PHONE_UPDATED',
  FORM_SUPPORT_EMAIL_UPDATED = 'FORM_SUPPORT_EMAIL_UPDATED',
  FORM_SUPPORT_ONLINE_UPDATED = 'FORM_SUPPORT_ONLINE_UPDATED',
  FORM_PRIVACY_NOTICE_UPDATED = 'FORM_PRIVACY_NOTICE_UPDATED',
  FORM_NOTIFICATION_EMAIL_UPDATED = 'FORM_NOTIFICATION_EMAIL_UPDATED',
  FORM_SUBMISSION_GUIDANCE_UPDATED = 'FORM_SUBMISSION_GUIDANCE_UPDATED',
  FORM_JSON_UPLOADED = 'FORM_JSON_UPLOADED',
  FORM_JSON_DOWNLOADED = 'FORM_JSON_DOWNLOADED',
  FORM_DRAFT_CREATED_FROM_LIVE = 'FORM_DRAFT_CREATED_FROM_LIVE',
  FORM_LIVE_CREATED_FROM_DRAFT = 'FORM_LIVE_CREATED_FROM_DRAFT',
  FORM_DRAFT_DELETED = 'FORM_DRAFT_DELETED',
  FORM_MIGRATED = 'FORM_MIGRATED',
  FORM_UPDATED = 'FORM_UPDATED'
}

export enum FormDefinitionRequestType {
  UPDATE_DRAFT = 'UPDATE_DRAFT',
  CREATE_COMPONENT = 'CREATE_COMPONENT',
  UPDATE_COMPONENT = 'UPDATE_COMPONENT',
  DELETE_COMPONENT = 'DELETE_COMPONENT',
  ADD_CONDITION = 'ADD_CONDITION',
  UPDATE_CONDITION = 'UPDATE_CONDITION',
  REMOVE_CONDITION = 'REMOVE_CONDITION',
  REORDER_PAGES = 'REORDER_PAGES',
  REORDER_COMPONENTS = 'REORDER_COMPONENTS',
  ADD_LIST = 'ADD_LIST',
  UPDATE_LIST = 'UPDATE_LIST',
  REMOVE_LIST = 'REMOVE_LIST',
  CREATE_PAGE = 'CREATE_PAGE',
  UPDATE_PAGE_FIELDS = 'UPDATE_PAGE_FIELDS',
  DELETE_PAGE = 'DELETE_PAGE'
}
