export enum AuditEventMessageCategory {
  FORM = 'FORM',
  ENTITLEMENT = 'ENTITLEMENT'
}

export enum AuditEventMessageSubCategory {
  FORM_METADATA = 'FORM_METADATA',
  FORM_DEFINITION = 'FORM_DEFINITION',
  FORM_SUBMISSION = 'FORM_SUBMISSION'
}

export enum AuditEventMessageType {
  FORM_CREATED = 'FORM_CREATED',
  FORM_PUBLISHED = 'FORM_PUBLISHED',
  FORM_NAME_UPDATED = 'FORM_NAME_UPDATED',
  FORM_ORGANISATION_UPDATED = 'FORM_ORGANISATION_UPDATED',
  FORM_TEAM_NAME_UPDATED = 'FORM_TEAM_NAME_UPDATED',
  FORM_TEAM_EMAIL_UPDATED = 'FORM_TEAM_EMAIL_UPDATED',
  FORM_SUPPORT_PHONE_UPDATED = 'FORM_SUPPORT_PHONE_UPDATED',
  FORM_SUPPORT_EMAIL_UPDATED = 'FORM_SUPPORT_EMAIL_UPDATED',
  FORM_SUPPORT_LINK_UPDATED = 'FORM_SUPPORT_LINK_UPDATED',
  FORM_PRIVACY_POLICY_LINK_UPDATED = 'FORM_PRIVACY_POLICY_LINK_UPDATED',
  FORM_NOTIFICATION_EMAIL_UPDATED = 'FORM_NOTIFICATION_EMAIL_UPDATED',
  FORM_SUBMISSION_GUIDANCE_UPDATED = 'FORM_SUBMISSION_GUIDANCE_UPDATED',
  FORM_JSON_UPLOADED = 'FORM_JSON_UPLOADED',
  FORM_JSON_DOWNLOADED = 'FORM_JSON_DOWNLOADED',
  FORM_DRAFT_CREATED_FROM_LIVE = 'FORM_DRAFT_CREATED_FROM_LIVE',
  FORM_DRAFT_DELETED = 'FORM_DRAFT_DELETED',
  FORM_MIGRATED = 'FORM_MIGRATED',
  FORM_UPDATED = 'FORM_UPDATED'
}
