export enum AuditEventMessageSchemaVersion {
  V1 = 1
}

export enum AuditEventMessageCategory {
  FORM = 'FORM',
  ENTITLEMENT = 'ENTITLEMENT',
  AUTHENTICATION = 'AUTHENTICATION'
}

export enum AuditEventMessageSource {
  FORMS_MANAGER = 'FORMS_MANAGER',
  FORMS_DESIGNER = 'FORMS_DESIGNER',
  ENTITLEMENT = 'ENTITLEMENT',
  AUTHENTICATION = 'AUTHENTICATION'
}

export enum AuditEventMessageType {
  // FORM message types
  FORM_CREATED = 'FORM_CREATED',
  FORM_TITLE_UPDATED = 'FORM_TITLE_UPDATED',
  FORM_ORGANISATION_UPDATED = 'FORM_ORGANISATION_UPDATED',
  FORM_TEAM_NAME_UPDATED = 'FORM_TEAM_NAME_UPDATED',
  FORM_TEAM_EMAIL_UPDATED = 'FORM_TEAM_EMAIL_UPDATED',
  FORM_SUPPORT_CONTACT_UPDATED = 'FORM_SUPPORT_CONTACT_UPDATED',
  FORM_SUPPORT_PHONE_UPDATED = 'FORM_SUPPORT_PHONE_UPDATED',
  FORM_SUPPORT_EMAIL_UPDATED = 'FORM_SUPPORT_EMAIL_UPDATED',
  FORM_SUPPORT_ONLINE_UPDATED = 'FORM_SUPPORT_ONLINE_UPDATED',
  FORM_PRIVACY_NOTICE_UPDATED = 'FORM_PRIVACY_NOTICE_UPDATED',
  FORM_NOTIFICATION_EMAIL_UPDATED = 'FORM_NOTIFICATION_EMAIL_UPDATED',
  FORM_SUBMISSION_GUIDANCE_UPDATED = 'FORM_SUBMISSION_GUIDANCE_UPDATED',
  FORM_JSON_UPLOADED = 'FORM_JSON_UPLOADED',
  FORM_JSON_DOWNLOADED = 'FORM_JSON_DOWNLOADED',
  FORM_FILE_DOWNLOADED = 'FORM_FILE_DOWNLOADED',
  FORM_DRAFT_CREATED_FROM_LIVE = 'FORM_DRAFT_CREATED_FROM_LIVE',
  FORM_LIVE_CREATED_FROM_DRAFT = 'FORM_LIVE_CREATED_FROM_DRAFT',
  FORM_DRAFT_DELETED = 'FORM_DRAFT_DELETED',
  FORM_MIGRATED = 'FORM_MIGRATED',
  FORM_UPDATED = 'FORM_UPDATED',

  // ENTITLEMENT message types
  ENTITLEMENT_CREATED = 'ENTITLEMENT_CREATED',
  ENTITLEMENT_UPDATED = 'ENTITLEMENT_UPDATED',
  ENTITLEMENT_DELETED = 'ENTITLEMENT_DELETED',

  // AUTHENTICATION message types
  AUTHENTICATION_LOGIN = 'AUTHENTICATION_LOGIN',
  AUTHENTICATION_LOGOUT_MANUAL = 'AUTHENTICATION_LOGOUT_MANUAL',
  AUTHENTICATION_LOGOUT_AUTO = 'AUTHENTICATION_LOGOUT_AUTO',
  AUTHENTICATION_LOGOUT_DIFFERENT_DEVICE = 'AUTHENTICATION_LOGOUT_DIFFERENT_DEVICE'
}

export enum FormDefinitionRequestType {
  REPLACE_DRAFT = 'REPLACE_DRAFT',
  CREATE_COMPONENT = 'CREATE_COMPONENT',
  UPDATE_COMPONENT = 'UPDATE_COMPONENT',
  DELETE_COMPONENT = 'DELETE_COMPONENT',
  CREATE_CONDITION = 'CREATE_CONDITION',
  UPDATE_CONDITION = 'UPDATE_CONDITION',
  DELETE_CONDITION = 'DELETE_CONDITION',
  REORDER_PAGES = 'REORDER_PAGES',
  REORDER_COMPONENTS = 'REORDER_COMPONENTS',
  CREATE_LIST = 'CREATE_LIST',
  UPDATE_LIST = 'UPDATE_LIST',
  DELETE_LIST = 'DELETE_LIST',
  CREATE_PAGE = 'CREATE_PAGE',
  UPDATE_PAGE_FIELDS = 'UPDATE_PAGE_FIELDS',
  DELETE_PAGE = 'DELETE_PAGE',
  REPOSITION_SUMMARY = 'REPOSITION_SUMMARY'
}
