import '@defra/forms-engine-plugin/templates/preview.html'
// import '@defra/forms-engine-plugin/controllers/QuestionPageController.js'
// import '@defra/forms-engine-plugin/components/helpers.js'
// import '@defra/forms-engine-plugin/components/evaluate-template.js'
import '@defra/forms-engine-plugin/components/AutocompleteField.js'
import '@defra/forms-engine-plugin/components/CheckboxesField.js'
// import '@defra/forms-engine-plugin/components/DatePartsField.js'
// import '@defra/forms-engine-plugin/components/ComponentCollection.js'
import '@defra/forms-engine-plugin/components/Details.js'
import '@defra/forms-engine-plugin/components/EmailAddressField.js'
// import '@defra/forms-engine-plugin/components/FileUploadField.js'
// import '@defra/forms-engine-plugin/components/helpers.js'
import '@defra/forms-engine-plugin/components/Html.js'
import '@defra/forms-engine-plugin/components/InsetText.js'
import '@defra/forms-engine-plugin/components/List.js'
import '@defra/forms-engine-plugin/components/ListFormComponent.js'
import '@defra/forms-engine-plugin/components/Markdown.js'
// import '@defra/forms-engine-plugin/components/MonthYearField.js'
import '@defra/forms-engine-plugin/components/MultilineTextField.js'
import '@defra/forms-engine-plugin/components/NumberField.js'
import '@defra/forms-engine-plugin/components/RadiosField.js'
import '@defra/forms-engine-plugin/components/SelectField.js'
import '@defra/forms-engine-plugin/components/SelectionControlField.js'
// import '@defra/forms-engine-plugin/components/TelephoneNumberField.js'
import '@defra/forms-engine-plugin/components/TextField.js'
// import '@defra/forms-engine-plugin/components/UkAddressField.js'
// import '@defra/forms-engine-plugin/components/YesNoField.js'
import '@defra/forms-engine-plugin/components/test.js'
// import '@defra/forms-engine-plugin/components/helpers-pure.js'
export function setupPagePreview() {
  // test
}
