export enum ComponentTypeEnum {
  TextField = 'TextField',
  MultilineTextField = 'MultilineTextField',
  YesNoField = 'YesNoField',
  DateField = 'DateField',
  TimeField = 'TimeField',
  DateTimeField = 'DateTimeField',
  DatePartsField = 'DatePartsField',
  MonthYearField = 'MonthYearField',
  DateTimePartsField = 'DateTimePartsField',
  SelectField = 'SelectField',
  AutocompleteField = 'AutocompleteField',
  RadiosField = 'RadiosField',
  CheckboxesField = 'CheckboxesField',
  NumberField = 'NumberField',
  UkAddressField = 'UkAddressField',
  TelephoneNumberField = 'TelephoneNumberField',
  EmailAddressField = 'EmailAddressField',
  FileUploadField = 'FileUploadField',
  Html = 'Html',
  InsetText = 'InsetText',
  Details = 'Details',
  List = 'List',
  WebsiteField = 'WebsiteField'
}
