export enum ComponentType {
  TextField = 'TextField',
  MultilineTextField = 'MultilineTextField',
  YesNoField = 'YesNoField',
  TimeField = 'TimeField',
  DatePartsField = 'DatePartsField',
  MonthYearField = 'MonthYearField',
  SelectField = 'SelectField',
  AutocompleteField = 'AutocompleteField',
  RadiosField = 'RadiosField',
  CheckboxesField = 'CheckboxesField',
  NumberField = 'NumberField',
  UkAddressField = 'UkAddressField',
  TelephoneNumberField = 'TelephoneNumberField',
  EmailAddressField = 'EmailAddressField',
  Html = 'Html',
  InsetText = 'InsetText',
  Details = 'Details',
  List = 'List'
}
