export enum ListActions {
  EDIT_TITLE = 'EDIT_TITLE',
  EDIT_TYPE = 'EDIT_TYPE',

  SET_SELECTED_LIST = 'SET_SELECTED_LIST',
  ADD_NEW_LIST = 'ADD_NEW_LIST',

  ADD_LIST_ITEM = 'ADD_LIST_ITEM',
  EDIT_LIST_ITEM = 'EDIT_LIST_ITEM',

  EDIT_LIST_ITEM_TEXT = 'EDIT_LIST_ITEM_TEXT',
  EDIT_LIST_ITEM_DESCRIPTION = 'EDIT_LIST_ITEM_DESCRIPTION',
  EDIT_LIST_ITEM_VALUE = 'EDIT_LIST_ITEM_VALUE',
  EDIT_LIST_ITEM_CONDITION = 'EDIT_LIST_ITEM_CONDITION',

  LIST_VALIDATION_ERRORS = 'LIST_VALIDATION_ERRORS',
  LIST_ITEM_VALIDATION_ERRORS = 'LIST_ITEM_VALIDATION_ERRORS'
}
