name: Post PR to Slack

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - closed

env:
  CONFIG: |
    {
      "opened": {
        "icon": ":large_yellow_circle:",
        "status": "opened"
      },
      "ready_for_review": {
        "icon": ":large_yellow_circle:",
        "status": "ready for review"
      },
      "reopened": {
        "icon": ":large_yellow_circle:",
        "status": "reopened"
      },
      "closed": {
        "icon": "${{ github.event.pull_request.merged && ':white_check_mark:' || ':wastebasket:' }}",
        "status": "${{ github.event.pull_request.merged && 'merged' || 'closed' }}"
      }
    }

jobs:
  notify:
    name: Slack notify
    runs-on: ubuntu-latest

    steps:
      - name: Post to Slack
        uses: slackapi/slack-github-action@v1.26.0

        env:
          ACTION_ICON: ${{ fromJSON(env.CONFIG)[github.event.action].icon }}
          ACTION_STATUS: ${{ fromJSON(env.CONFIG)[github.event.action].status }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

        with:
          channel-id: ${{ vars.SLACK_CHANNEL_ID }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ env.ACTION_ICON }} *${{ github.event.repository.name }}:* Pull request ${{ env.ACTION_STATUS }}\n<${{ github.event.pull_request.html_url }}>"
                  }
                }
              ]
            }
